package ws.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-05-17T07:17:30.962+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://cxf.ws/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "f", targetNamespace = "http://cxf.ws/", className = "ws.cxf.F")
    @WebMethod
    @ResponseWrapper(localName = "fResponse", targetNamespace = "http://cxf.ws/", className = "ws.cxf.FResponse")
    public java.lang.String f(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://cxf.ws/", className = "ws.cxf.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://cxf.ws/", className = "ws.cxf.GetUserResponse")
    public ws.cxf.User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "f2", targetNamespace = "http://cxf.ws/", className = "ws.cxf.F2")
    @WebMethod
    @ResponseWrapper(localName = "f2Response", targetNamespace = "http://cxf.ws/", className = "ws.cxf.F2Response")
    public java.lang.String f2(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1
    );
}
