
package ws.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISurveyServiceService", targetNamespace = "http://cxf.ws/", wsdlLocation = "http://localhost:8080/cxfserver/SurveyWebService?wsdl")
public class ISurveyServiceService
    extends Service
{

    private final static URL ISURVEYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ISURVEYSERVICESERVICE_EXCEPTION;
    private final static QName ISURVEYSERVICESERVICE_QNAME = new QName("http://cxf.ws/", "ISurveyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/cxfserver/SurveyWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISURVEYSERVICESERVICE_WSDL_LOCATION = url;
        ISURVEYSERVICESERVICE_EXCEPTION = e;
    }

    public ISurveyServiceService() {
        super(__getWsdlLocation(), ISURVEYSERVICESERVICE_QNAME);
    }

    public ISurveyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISURVEYSERVICESERVICE_QNAME, features);
    }

    public ISurveyServiceService(URL wsdlLocation) {
        super(wsdlLocation, ISURVEYSERVICESERVICE_QNAME);
    }

    public ISurveyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISURVEYSERVICESERVICE_QNAME, features);
    }

    public ISurveyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISurveyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISurveyService
     */
    @WebEndpoint(name = "ISurveyServicePort")
    public ISurveyService getISurveyServicePort() {
        return super.getPort(new QName("http://cxf.ws/", "ISurveyServicePort"), ISurveyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISurveyService
     */
    @WebEndpoint(name = "ISurveyServicePort")
    public ISurveyService getISurveyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.ws/", "ISurveyServicePort"), ISurveyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISURVEYSERVICESERVICE_EXCEPTION!= null) {
            throw ISURVEYSERVICESERVICE_EXCEPTION;
        }
        return ISURVEYSERVICESERVICE_WSDL_LOCATION;
    }

}
